// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/insect_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/insect_service_interface.go -destination=internal/services/mock/mock_insect_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dtos "github.com/Masaaki618/insectfood-backend/internal/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockIInsectService is a mock of IInsectService interface.
type MockIInsectService struct {
	ctrl     *gomock.Controller
	recorder *MockIInsectServiceMockRecorder
	isgomock struct{}
}

// MockIInsectServiceMockRecorder is the mock recorder for MockIInsectService.
type MockIInsectServiceMockRecorder struct {
	mock *MockIInsectService
}

// NewMockIInsectService creates a new mock instance.
func NewMockIInsectService(ctrl *gomock.Controller) *MockIInsectService {
	mock := &MockIInsectService{ctrl: ctrl}
	mock.recorder = &MockIInsectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInsectService) EXPECT() *MockIInsectServiceMockRecorder {
	return m.recorder
}

// GetInsectByID mocks base method.
func (m *MockIInsectService) GetInsectByID(ctx context.Context, insectID uint) (*dtos.InsectDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInsectByID", ctx, insectID)
	ret0, _ := ret[0].(*dtos.InsectDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInsectByID indicates an expected call of GetInsectByID.
func (mr *MockIInsectServiceMockRecorder) GetInsectByID(ctx, insectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInsectByID", reflect.TypeOf((*MockIInsectService)(nil).GetInsectByID), ctx, insectID)
}

// GetInsects mocks base method.
func (m *MockIInsectService) GetInsects(ctx context.Context) ([]dtos.InsectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInsects", ctx)
	ret0, _ := ret[0].([]dtos.InsectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInsects indicates an expected call of GetInsects.
func (mr *MockIInsectServiceMockRecorder) GetInsects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInsects", reflect.TypeOf((*MockIInsectService)(nil).GetInsects), ctx)
}
