// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/diagnosis_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/diagnosis_service_interface.go -destination=internal/services/mock/mock_diagnosis_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dtos "github.com/Masaaki618/insectfood-backend/internal/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockIDiagnosisService is a mock of IDiagnosisService interface.
type MockIDiagnosisService struct {
	ctrl     *gomock.Controller
	recorder *MockIDiagnosisServiceMockRecorder
	isgomock struct{}
}

// MockIDiagnosisServiceMockRecorder is the mock recorder for MockIDiagnosisService.
type MockIDiagnosisServiceMockRecorder struct {
	mock *MockIDiagnosisService
}

// NewMockIDiagnosisService creates a new mock instance.
func NewMockIDiagnosisService(ctrl *gomock.Controller) *MockIDiagnosisService {
	mock := &MockIDiagnosisService{ctrl: ctrl}
	mock.recorder = &MockIDiagnosisServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDiagnosisService) EXPECT() *MockIDiagnosisServiceMockRecorder {
	return m.recorder
}

// Diagnose mocks base method.
func (m *MockIDiagnosisService) Diagnose(ctx context.Context, req dtos.DiagnosisRequest) (*dtos.DiagnosisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Diagnose", ctx, req)
	ret0, _ := ret[0].(*dtos.DiagnosisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Diagnose indicates an expected call of Diagnose.
func (mr *MockIDiagnosisServiceMockRecorder) Diagnose(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Diagnose", reflect.TypeOf((*MockIDiagnosisService)(nil).Diagnose), ctx, req)
}
