// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/question_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/question_service_interface.go -destination=internal/services/mock/mock_question_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dtos "github.com/Masaaki618/insectfood-backend/internal/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockIQuestionService is a mock of IQuestionService interface.
type MockIQuestionService struct {
	ctrl     *gomock.Controller
	recorder *MockIQuestionServiceMockRecorder
	isgomock struct{}
}

// MockIQuestionServiceMockRecorder is the mock recorder for MockIQuestionService.
type MockIQuestionServiceMockRecorder struct {
	mock *MockIQuestionService
}

// NewMockIQuestionService creates a new mock instance.
func NewMockIQuestionService(ctrl *gomock.Controller) *MockIQuestionService {
	mock := &MockIQuestionService{ctrl: ctrl}
	mock.recorder = &MockIQuestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuestionService) EXPECT() *MockIQuestionServiceMockRecorder {
	return m.recorder
}

// GetQuestions mocks base method.
func (m *MockIQuestionService) GetQuestions(ctx context.Context) ([]dtos.QuestionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestions", ctx)
	ret0, _ := ret[0].([]dtos.QuestionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestions indicates an expected call of GetQuestions.
func (mr *MockIQuestionServiceMockRecorder) GetQuestions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestions", reflect.TypeOf((*MockIQuestionService)(nil).GetQuestions), ctx)
}
