// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/ai/claude_client_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/ai/claude_client_interface.go -destination=internal/infrastructure/ai/mock/mock_claude_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/Masaaki618/insectfood-backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIClaudeClient is a mock of IClaudeClient interface.
type MockIClaudeClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClaudeClientMockRecorder
	isgomock struct{}
}

// MockIClaudeClientMockRecorder is the mock recorder for MockIClaudeClient.
type MockIClaudeClientMockRecorder struct {
	mock *MockIClaudeClient
}

// NewMockIClaudeClient creates a new mock instance.
func NewMockIClaudeClient(ctrl *gomock.Controller) *MockIClaudeClient {
	mock := &MockIClaudeClient{ctrl: ctrl}
	mock.recorder = &MockIClaudeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClaudeClient) EXPECT() *MockIClaudeClientMockRecorder {
	return m.recorder
}

// GenerateDiagnosisResult mocks base method.
func (m *MockIClaudeClient) GenerateDiagnosisResult(ctx context.Context, visual, physical, mental uint8, insects []models.Insect) (uint, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDiagnosisResult", ctx, visual, physical, mental, insects)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateDiagnosisResult indicates an expected call of GenerateDiagnosisResult.
func (mr *MockIClaudeClientMockRecorder) GenerateDiagnosisResult(ctx, visual, physical, mental, insects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDiagnosisResult", reflect.TypeOf((*MockIClaudeClient)(nil).GenerateDiagnosisResult), ctx, visual, physical, mental, insects)
}

// GenerateInsectComment mocks base method.
func (m *MockIClaudeClient) GenerateInsectComment(ctx context.Context, insect *models.Insect) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInsectComment", ctx, insect)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInsectComment indicates an expected call of GenerateInsectComment.
func (mr *MockIClaudeClientMockRecorder) GenerateInsectComment(ctx, insect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInsectComment", reflect.TypeOf((*MockIClaudeClient)(nil).GenerateInsectComment), ctx, insect)
}
