// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/question_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/question_repository_interface.go -destination=internal/repositories/mock/mock_question_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/Masaaki618/insectfood-backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIQuestionRepository is a mock of IQuestionRepository interface.
type MockIQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockIQuestionRepositoryMockRecorder is the mock recorder for MockIQuestionRepository.
type MockIQuestionRepositoryMockRecorder struct {
	mock *MockIQuestionRepository
}

// NewMockIQuestionRepository creates a new mock instance.
func NewMockIQuestionRepository(ctrl *gomock.Controller) *MockIQuestionRepository {
	mock := &MockIQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockIQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuestionRepository) EXPECT() *MockIQuestionRepositoryMockRecorder {
	return m.recorder
}

// GetRandomQuestionsByCategory mocks base method.
func (m *MockIQuestionRepository) GetRandomQuestionsByCategory(ctx context.Context, category models.QuestionCategory, limit int) ([]models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomQuestionsByCategory", ctx, category, limit)
	ret0, _ := ret[0].([]models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomQuestionsByCategory indicates an expected call of GetRandomQuestionsByCategory.
func (mr *MockIQuestionRepositoryMockRecorder) GetRandomQuestionsByCategory(ctx, category, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomQuestionsByCategory", reflect.TypeOf((*MockIQuestionRepository)(nil).GetRandomQuestionsByCategory), ctx, category, limit)
}
