// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/insect_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/insect_repository_interface.go -destination=internal/repositories/mock/mock_insect_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/Masaaki618/insectfood-backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIInsectRepository is a mock of IInsectRepository interface.
type MockIInsectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInsectRepositoryMockRecorder
	isgomock struct{}
}

// MockIInsectRepositoryMockRecorder is the mock recorder for MockIInsectRepository.
type MockIInsectRepositoryMockRecorder struct {
	mock *MockIInsectRepository
}

// NewMockIInsectRepository creates a new mock instance.
func NewMockIInsectRepository(ctrl *gomock.Controller) *MockIInsectRepository {
	mock := &MockIInsectRepository{ctrl: ctrl}
	mock.recorder = &MockIInsectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInsectRepository) EXPECT() *MockIInsectRepositoryMockRecorder {
	return m.recorder
}

// GetInsectByID mocks base method.
func (m *MockIInsectRepository) GetInsectByID(ctx context.Context, insectID uint) (*models.Insect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInsectByID", ctx, insectID)
	ret0, _ := ret[0].(*models.Insect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInsectByID indicates an expected call of GetInsectByID.
func (mr *MockIInsectRepositoryMockRecorder) GetInsectByID(ctx, insectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInsectByID", reflect.TypeOf((*MockIInsectRepository)(nil).GetInsectByID), ctx, insectID)
}

// GetInsects mocks base method.
func (m *MockIInsectRepository) GetInsects(ctx context.Context) ([]models.Insect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInsects", ctx)
	ret0, _ := ret[0].([]models.Insect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInsects indicates an expected call of GetInsects.
func (mr *MockIInsectRepositoryMockRecorder) GetInsects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInsects", reflect.TypeOf((*MockIInsectRepository)(nil).GetInsects), ctx)
}

// GetRadarChartByInsectID mocks base method.
func (m *MockIInsectRepository) GetRadarChartByInsectID(ctx context.Context, insectID uint) (*models.RadarChart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadarChartByInsectID", ctx, insectID)
	ret0, _ := ret[0].(*models.RadarChart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRadarChartByInsectID indicates an expected call of GetRadarChartByInsectID.
func (mr *MockIInsectRepositoryMockRecorder) GetRadarChartByInsectID(ctx, insectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadarChartByInsectID", reflect.TypeOf((*MockIInsectRepository)(nil).GetRadarChartByInsectID), ctx, insectID)
}
